name: myenv
channels:
  - defaults
  - conda-forge  # conda-forge 채널 추가
dependencies:
  - python=3.10
  - aioredis=2.0.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - async-timeout=4.0.3
  - beautifulsoup4=4.12.2
  - cement=2.8.2
  - certifi=2022.5.18.1
  - charset-normalizer=2.0.12
  - colorama=0.4.3
  - exceptiongroup=1.1.3
  - fastapi=0.104.1
  - future=0.16.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.25.1
  - idna=3.3
  - jmespath=0.10.0
  - numpy=1.26.2
  - pandas=2.1.3
  - pathspec=0.9.0
  - pydantic=2.5.0
  - pydantic_core=2.14.1
  - pypiwin32=223
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - pywin32=304
  - PyYAML=5.4.1
  - hiredis=2.0.0
  - redis=5.0.1
  - requests=2.26.0
  - semantic-version=2.8.5
  - six=1.14.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - starlette=0.27.0
  - termcolor=1.1.0
  - typing_extensions=4.8.0
  - tzdata=2023.3
  - urllib3=1.26.9
  - wcwidth=0.1.9
